### ISSUE TITLE
Any plan on a new release? [Question]

### ISSUE THREAD

**Issue by xpirad** [derrekr/fastboot3DS#43]
It has been a year since the last release, and there have been many new commits, will you consider making a new official release?

Thanks!

**Comment by profi200** [comment]
No new functionality has been added since then. It's mainly small bug fixes and some code has been only pushed because it could be of use later (for example audio stuff) and for documentations sake.

Maybe we will make a new release soon. But before that some other code must make it into the repo namely the final screen init fix. And then lots of testing needs to be done. So unsure when we will make a new release.

**Comment by xpirad** [comment]
I see, thanks for the explanation!
